### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by AlexMokin** [AndreiManya/slack#1]
The layout seem to be pretty close. Although there are some elements that original massenger doesn't have.

Please fix this
1. Change the colors so it looks like original. 
2. On mobile screen message box at the bootom is cut, see image

![image](https://user-images.githubusercontent.com/7272208/87836583-30a6a300-c899-11ea-9132-ce5dbaf40a2a.png)

**Comment by AndreiManya** [comment]
Fixed
This issue was opened 7 days ago, but i didn`t saw notification, srry for waiting

**Comment by ilya4321** [comment]
![image](https://user-images.githubusercontent.com/5592397/88433523-ed06e880-ce06-11ea-826c-77f1bc3e8567.png)

**Comment by AndreiManya** [comment]
Done

**Comment by ilya4321** [comment]
![image](https://user-images.githubusercontent.com/5592397/88488362-8237e780-cf95-11ea-8b55-b13199dea087.png)

 - I've also noticed the "redundant margin" from previous comment on big screens is not fixed.

**Comment by AndreiManya** [comment]
Fixed

**Comment by ilya4321** [comment]
Yes, looks good! Thanks for the efforts. The messenger is accepted. We will b checking your js tasks soon
